import collectionDaily from "@/assets/collection-daily.jpg"
import collectionBridal from "@/assets/collection-bridal.jpg"
import collectionAntique from "@/assets/collection-antique.jpg"
import collectionDiamond from "@/assets/collection-diamond.jpg"
import craftsmanship from "@/assets/craftsmanship.jpg"
import hero from "@/assets/hero-jewellery.jpg"
import { slugify } from "./utils"
import type { CategoryItem, CollectionItem, ProductItem, ShopDb } from "./types"

const collections: CollectionItem[] = [
  { id: "col_gold", name: "Gold", slug: "gold", image: collectionDaily, displayOrder: 1, status: "active" },
  { id: "col_silver", name: "Silver", slug: "silver", image: collectionAntique, displayOrder: 2, status: "active" },
  { id: "col_platinum", name: "Platinum", slug: "platinum", image: craftsmanship, displayOrder: 3, status: "active" },
  { id: "col_diamond", name: "Diamond", slug: "diamond", image: collectionDiamond, displayOrder: 4, status: "active" },
]

const categories: CategoryItem[] = [
  { id: "cat_gold_rings", collectionId: "col_gold", name: "Rings", slug: "rings", image: collectionBridal, displayOrder: 1, status: "active" },
  { id: "cat_gold_chains", collectionId: "col_gold", name: "Chains", slug: "chains", image: hero, displayOrder: 2, status: "active" },
  { id: "cat_gold_necklaces", collectionId: "col_gold", name: "Necklaces", slug: "necklaces", image: collectionDaily, displayOrder: 3, status: "active" },
  { id: "cat_gold_bangles", collectionId: "col_gold", name: "Bangles", slug: "bangles", image: collectionAntique, displayOrder: 4, status: "active" },
  { id: "cat_gold_bracelets", collectionId: "col_gold", name: "Bracelets", slug: "bracelets", image: craftsmanship, displayOrder: 5, status: "active" },
  { id: "cat_gold_earrings", collectionId: "col_gold", name: "Earrings", slug: "earrings", image: collectionDiamond, displayOrder: 6, status: "active" },
  { id: "cat_gold_pendants", collectionId: "col_gold", name: "Pendants", slug: "pendants", image: collectionBridal, displayOrder: 7, status: "active" },
  { id: "cat_gold_anklets", collectionId: "col_gold", name: "Anklets", slug: "anklets", image: collectionDaily, displayOrder: 8, status: "active" },
  { id: "cat_gold_coins", collectionId: "col_gold", name: "Coins", slug: "coins", image: hero, displayOrder: 9, status: "active" },

  { id: "cat_dia_rings", collectionId: "col_diamond", name: "Diamond Rings", slug: "diamond-rings", image: collectionDiamond, displayOrder: 1, status: "active" },
  { id: "cat_dia_necklaces", collectionId: "col_diamond", name: "Diamond Necklaces", slug: "diamond-necklaces", image: collectionBridal, displayOrder: 2, status: "active" },
  { id: "cat_dia_earrings", collectionId: "col_diamond", name: "Diamond Earrings", slug: "diamond-earrings", image: collectionDaily, displayOrder: 3, status: "active" },
  { id: "cat_dia_pendants", collectionId: "col_diamond", name: "Diamond Pendants", slug: "diamond-pendants", image: craftsmanship, displayOrder: 4, status: "active" },

  { id: "cat_silver_rings", collectionId: "col_silver", name: "Silver Rings", slug: "silver-rings", image: collectionAntique, displayOrder: 1, status: "active" },
  { id: "cat_silver_chains", collectionId: "col_silver", name: "Silver Chains", slug: "silver-chains", image: hero, displayOrder: 2, status: "active" },
  { id: "cat_silver_articles", collectionId: "col_silver", name: "Silver Articles", slug: "silver-articles", image: collectionDaily, displayOrder: 3, status: "active" },
  { id: "cat_silver_gifts", collectionId: "col_silver", name: "Silver Gifts", slug: "silver-gifts", image: collectionDiamond, displayOrder: 4, status: "active" },

  { id: "cat_pt_rings", collectionId: "col_platinum", name: "Platinum Rings", slug: "platinum-rings", image: collectionBridal, displayOrder: 1, status: "active" },
  { id: "cat_pt_chains", collectionId: "col_platinum", name: "Platinum Chains", slug: "platinum-chains", image: craftsmanship, displayOrder: 2, status: "active" },
  { id: "cat_pt_bracelets", collectionId: "col_platinum", name: "Platinum Bracelets", slug: "platinum-bracelets", image: collectionAntique, displayOrder: 3, status: "active" },
]

const productSeed: Array<Omit<ProductItem, "id" | "slug" | "images" | "featuredImageIndex"> & { imageSet: string[] }> = [
  {
    productCode: "GR1025",
    name: "Elegant Gold Ring",
    collectionId: "col_gold",
    categoryId: "cat_gold_rings",
    imageSet: [collectionBridal, collectionDaily, hero],
    grossWeight: 4.25,
    netWeight: 4.1,
    stoneWeight: 0,
    diamondWeight: 0,
    stoneAmount: 0,
    vaPercent: 12,
    vaam: 2200,
    purity: "22K",
    description: "A handcrafted ring with classic Kerala-inspired detailing.",
    stockQuantity: 1,
    estimatedPrice: 36500,
    status: "active",
    featured: true,
  },
  {
    productCode: "GC005",
    name: "Temple Gold Chain",
    collectionId: "col_gold",
    categoryId: "cat_gold_chains",
    imageSet: [hero, collectionAntique, collectionBridal],
    grossWeight: 12.5,
    netWeight: 12.2,
    stoneWeight: 0,
    diamondWeight: 0,
    stoneAmount: 0,
    vaPercent: 10,
    vaam: 6300,
    purity: "22K",
    description: "A rich temple-style chain suitable for festive wear.",
    stockQuantity: 8,
    estimatedPrice: 101000,
    status: "active",
    featured: false,
  },
  {
    productCode: "GN021",
    name: "Royal Gold Necklace",
    collectionId: "col_gold",
    categoryId: "cat_gold_necklaces",
    imageSet: [collectionDaily, collectionBridal, collectionDiamond],
    grossWeight: 22.9,
    netWeight: 22.3,
    stoneWeight: 0,
    diamondWeight: 0,
    stoneAmount: 0,
    vaPercent: 14,
    vaam: 14100,
    purity: "22K",
    description: "A ceremonial necklace with layered filigree accents.",
    stockQuantity: 4,
    estimatedPrice: 184000,
    status: "active",
    featured: true,
  },
  {
    productCode: "GB331",
    name: "Classic Gold Bangle",
    collectionId: "col_gold",
    categoryId: "cat_gold_bangles",
    imageSet: [collectionAntique, hero, craftsmanship],
    grossWeight: 15.25,
    netWeight: 14.95,
    stoneWeight: 0,
    diamondWeight: 0,
    stoneAmount: 0,
    vaPercent: 11,
    vaam: 7900,
    purity: "22K",
    description: "Bold everyday bangle with smooth polished finish.",
    stockQuantity: 6,
    estimatedPrice: 121000,
    status: "active",
    featured: false,
  },
  {
    productCode: "GE110",
    name: "Bloom Gold Earrings",
    collectionId: "col_gold",
    categoryId: "cat_gold_earrings",
    imageSet: [collectionDiamond, collectionDaily, hero],
    grossWeight: 6.1,
    netWeight: 5.9,
    stoneWeight: 0.1,
    diamondWeight: 0,
    stoneAmount: 1200,
    vaPercent: 13,
    vaam: 3200,
    purity: "22K",
    description: "Floral earrings designed for versatile styling.",
    stockQuantity: 10,
    estimatedPrice: 52800,
    status: "active",
    featured: false,
  },
  {
    productCode: "DP451",
    name: "Radiance Diamond Pendant",
    collectionId: "col_diamond",
    categoryId: "cat_dia_pendants",
    imageSet: [collectionDiamond, collectionBridal, craftsmanship],
    grossWeight: 5.4,
    netWeight: 4.8,
    stoneWeight: 0.3,
    diamondWeight: 0.32,
    stoneAmount: 18500,
    vaPercent: 8,
    vaam: 4600,
    purity: "18K",
    description: "A fine diamond pendant with halo stone setting.",
    stockQuantity: 2,
    estimatedPrice: 96200,
    status: "active",
    featured: true,
  },
  {
    productCode: "DR102",
    name: "Signature Diamond Ring",
    collectionId: "col_diamond",
    categoryId: "cat_dia_rings",
    imageSet: [collectionBridal, collectionDiamond, hero],
    grossWeight: 4.9,
    netWeight: 4.3,
    stoneWeight: 0.2,
    diamondWeight: 0.45,
    stoneAmount: 24800,
    vaPercent: 7,
    vaam: 3900,
    purity: "18K",
    description: "Solitaire-inspired ring with premium VS clarity stones.",
    stockQuantity: 1,
    estimatedPrice: 131000,
    status: "active",
    featured: true,
  },
  {
    productCode: "DN801",
    name: "Lustre Diamond Necklace",
    collectionId: "col_diamond",
    categoryId: "cat_dia_necklaces",
    imageSet: [collectionDiamond, collectionDaily, collectionBridal],
    grossWeight: 16.6,
    netWeight: 15.7,
    stoneWeight: 0.4,
    diamondWeight: 1.2,
    stoneAmount: 86000,
    vaPercent: 9,
    vaam: 13200,
    purity: "18K",
    description: "Statement necklace built for bridal and event wear.",
    stockQuantity: 3,
    estimatedPrice: 327000,
    status: "active",
    featured: false,
  },
  {
    productCode: "SE271",
    name: "Silver Edge Ring",
    collectionId: "col_silver",
    categoryId: "cat_silver_rings",
    imageSet: [collectionAntique, collectionDaily, hero],
    grossWeight: 5.7,
    netWeight: 5.4,
    stoneWeight: 0,
    diamondWeight: 0,
    stoneAmount: 0,
    vaPercent: 6,
    vaam: 600,
    purity: "925 Silver",
    description: "Minimal ring with polished edge profile.",
    stockQuantity: 12,
    estimatedPrice: 4200,
    status: "active",
    featured: false,
  },
  {
    productCode: "SC055",
    name: "Sterling Silver Chain",
    collectionId: "col_silver",
    categoryId: "cat_silver_chains",
    imageSet: [hero, collectionAntique, collectionDiamond],
    grossWeight: 14.8,
    netWeight: 14.1,
    stoneWeight: 0,
    diamondWeight: 0,
    stoneAmount: 0,
    vaPercent: 5,
    vaam: 820,
    purity: "925 Silver",
    description: "Durable sterling chain made for daily use.",
    stockQuantity: 7,
    estimatedPrice: 9700,
    status: "active",
    featured: false,
  },
  {
    productCode: "SG999",
    name: "Silver Gift Idol",
    collectionId: "col_silver",
    categoryId: "cat_silver_gifts",
    imageSet: [collectionDaily, collectionAntique, craftsmanship],
    grossWeight: 25.4,
    netWeight: 24.8,
    stoneWeight: 0,
    diamondWeight: 0,
    stoneAmount: 0,
    vaPercent: 4,
    vaam: 1200,
    purity: "999 Silver",
    description: "Intricately finished silver gift article.",
    stockQuantity: 1,
    estimatedPrice: 18800,
    status: "active",
    featured: true,
  },
  {
    productCode: "PR411",
    name: "Platinum Promise Ring",
    collectionId: "col_platinum",
    categoryId: "cat_pt_rings",
    imageSet: [collectionBridal, craftsmanship, collectionDiamond],
    grossWeight: 6.2,
    netWeight: 5.9,
    stoneWeight: 0.1,
    diamondWeight: 0.05,
    stoneAmount: 6200,
    vaPercent: 5,
    vaam: 4400,
    purity: "950 Platinum",
    description: "Clean platinum ring with subtle accent stones.",
    stockQuantity: 5,
    estimatedPrice: 71600,
    status: "active",
    featured: true,
  },
  {
    productCode: "PC221",
    name: "Platinum Link Chain",
    collectionId: "col_platinum",
    categoryId: "cat_pt_chains",
    imageSet: [craftsmanship, hero, collectionAntique],
    grossWeight: 9.3,
    netWeight: 8.8,
    stoneWeight: 0,
    diamondWeight: 0,
    stoneAmount: 0,
    vaPercent: 4,
    vaam: 3500,
    purity: "950 Platinum",
    description: "Contemporary link chain with balanced weight profile.",
    stockQuantity: 2,
    estimatedPrice: 98800,
    status: "active",
    featured: false,
  },
]

const products: ProductItem[] = productSeed.map((item) => ({
  ...item,
  id: `prd_${item.productCode.toLowerCase()}`,
  slug: slugify(`${item.name}-${item.productCode}`),
  images: item.imageSet,
  featuredImageIndex: 0,
}))

export const defaultShopDb: ShopDb = {
  collections,
  categories,
  products,
  quoteRequests: [],
  settings: {
    whatsappNumber: "+91 9746755852",
    shopBanner: "Discover handpicked collections crafted for life\'s celebrations.",
    seoTitle: "Shop Online | Ashok Gold & Diamonds",
    seoDescription: "Buy gold, diamond, silver, and platinum jewellery online from Ashok Gold & Diamonds.",
  },
}
