/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchemeRouteImport } from './routes/scheme'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions';
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy';
import { Route as RefundPolicyRouteImport } from './routes/refund-and-cancellation-policy';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemeRoute = SchemeRouteImport.update({
  id: '/scheme',
  path: '/scheme',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-and-cancellation-policy',
  path: '/refund-and-cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scheme': typeof SchemeRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation-policy': typeof RefundPolicyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scheme': typeof SchemeRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation-policy': typeof RefundPolicyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scheme': typeof SchemeRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation-policy': typeof RefundPolicyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scheme' | '/terms-and-conditions' | '/privacy-policy' | '/refund-and-cancellation-policy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scheme' | '/terms-and-conditions' | '/privacy-policy' | '/refund-and-cancellation-policy'
  id: '__root__' | '/' | '/scheme' | '/terms-and-conditions' | '/privacy-policy' | '/refund-and-cancellation-policy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchemeRoute: typeof SchemeRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheme': {
      id: '/scheme'
      path: '/scheme'
      fullPath: '/scheme'
      preLoaderRoute: typeof SchemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-and-cancellation-policy': {
      id: '/refund-and-cancellation-policy'
      path: '/refund-and-cancellation-policy'
      fullPath: '/refund-and-cancellation-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchemeRoute: SchemeRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
